# Generated by Django 3.2.14 on 2022-07-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='myDashId',
            field=models.CharField(max_length=120),
        ),
    ]
