# Generated by Django 3.2.14 on 2022-07-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_scrapeddata_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapeddata',
            old_name='myDashId',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='scrapeddata',
            old_name='owner',
            new_name='user_agent',
        ),
        migrations.AddField(
            model_name='mydashone',
            name='engineIsSafe',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
