# Generated by Django 4.0.6 on 2022-07-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20220725_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydashone',
            name='engineIsSafe',
            field=models.BooleanField(null=True),
        ),
    ]
